Repository wmde/fundraising-donations, pull requests merged in 2025-05, with the labels that each got.

#305 Do not send confirmation mail when donation is moderated
  src/Domain/Model/Donation.php
  tests/Unit/Domain/Model/DonationTest.php
Labels: Ready for review

#309 Rename "donation accepted" to "donation approved"
  src/DonationApprovedEventHandler.php
  tests/Integration/DonationApprovedEventHandlerTest.php
Labels: needs-major-release

#281 Add backup class for personal data
  src/DataAccess/Backup/DatabaseBackupClient.php
  src/DataAccess/Backup/PersonalDataBackup.php
  src/DataAccess/Backup/TableBackupConfiguration.php
  tests/Fixtures/DatabaseBackupClientSpy.php
  tests/Integration/DataAccess/PersonalDataBackupTest.php
Labels: Ready for review, needs-minor-release
